#ifndef LUFACONFIG_H_
#define LUFACONFIG_H_


#define USE_FLASH_DESCRIPTORS
#define USE_STATIC_OPTIONS               (USB_DEVICE_OPT_FULLSPEED | USB_OPT_REG_ENABLED | USB_OPT_AUTO_PLL)


#endif /* LUFACONFIG_H_ */